title: Learning with Me
tagline: Technical Blog Covering AI
description: Exploring artificial intelligence, machine learning, and software development through practical experiences and insights
url: 'https://pramodith.github.io'  # Replace with your GitHub username
baseurl: ''

# Theme settings
remote_theme: jekyll-theme-chirpy
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed

# Navigation Links
nav:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: Machine Learning
    url: /categories/machine-learning/
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/
  - title: About
    url: /about/

# Author Information
author:
  name: Pramodith B
  bio: Software developer passionate about AI and machine learning
  # Add your social media links
  social:
    linkedin: https://www.linkedin.com/in/pramodith/  # Optional

# Jekyll Settings
paginate: 10
permalink: /:year/:month/:day/:title/

# Additional settings for better SEO and site performance
timezone: Ireland/Dublin  # Change to your timezone
lang: en